---
title: "Random forest raw data down sample"
author: "Hui Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(caret)
library(randomForest)
library(ranger)
library(ggplot2)
library(tictoc)
library(data.table)
library(ordinalForest)
```

## 1. Load data

```{r}
train_raw <- read.csv("train_raw.csv", header = TRUE)
test_raw <- read.csv("test_raw.csv", header = TRUE)
```


## 2.check feature type and convert character feature to factor


```{r}
# Check feature type of train_raw data
#str(train_raw)

# Convert character to factor in train_raw data
train_raw$race <- factor(train_raw$race)
train_raw$gender <- factor(train_raw$gender)
train_raw$age <- factor(train_raw$age, order = TRUE, levels = c("[0-10)", "[10-20)", "[20-30)", "[30-40)", "[40-50)", "[50-60)", "[60-70)", "[70-80)", "[80-90)", "[90-100)"))
train_raw$diag_1 <- factor(train_raw$diag_1 )
train_raw$diag_2 <- factor(train_raw$diag_2)
train_raw$diag_3 <- factor(train_raw$diag_3)
train_raw$A1Cresult <- factor(train_raw$A1Cresult)
train_raw$metformin <- factor(train_raw$metformin)
train_raw$glipizide <- factor(train_raw$glipizide)
train_raw$glyburide <- factor(train_raw$glyburide)
train_raw$pioglitazone <- factor(train_raw$pioglitazone)
train_raw$rosiglitazone <- factor(train_raw$rosiglitazone)
train_raw$insulin  <- factor(train_raw$insulin )
train_raw$change <- factor(train_raw$change)
train_raw$diabetesMed <- factor(train_raw$diabetesMed)
train_raw$readmitted <- factor(train_raw$readmitted, order = TRUE, levels = c("NO", ">30", "<30"))
train_raw$admission_source <- factor(train_raw$admission_source)
train_raw$discharge_disposition <- factor(train_raw$discharge_disposition)
train_raw$admission_type <- factor(train_raw$admission_type)

# Check feature type in train_raw data after conversion
# str(train_raw)

# Convert character to factor in test_raw data
test_raw$race <- factor(test_raw$race)
test_raw$gender <- factor(test_raw$gender)
test_raw$age <- factor(test_raw$age, order = TRUE, levels = c("[0-10)", "[10-20)", "[20-30)", "[30-40)", "[40-50)", "[50-60)", "[60-70)", "[70-80)", "[80-90)", "[90-100)"))
test_raw$diag_1 <- factor(test_raw$diag_1 )
test_raw$diag_2 <- factor(test_raw$diag_2)
test_raw$diag_3 <- factor(test_raw$diag_3)
test_raw$A1Cresult <- factor(test_raw$A1Cresult)
test_raw$metformin <- factor(test_raw$metformin)
test_raw$glipizide <- factor(test_raw$glipizide)
test_raw$glyburide <- factor(test_raw$glyburide)
test_raw$pioglitazone <- factor(test_raw$pioglitazone)
test_raw$rosiglitazone <- factor(test_raw$rosiglitazone)
test_raw$insulin  <- factor(test_raw$insulin )
test_raw$change <- factor(test_raw$change)
test_raw$diabetesMed <- factor(test_raw$diabetesMed)
test_raw$readmitted <- factor(test_raw$readmitted, order = TRUE, levels = c("NO", ">30", "<30"))
test_raw$admission_source <- factor(test_raw$admission_source)
test_raw$discharge_disposition <- factor(test_raw$discharge_disposition)
test_raw$admission_type <- factor(test_raw$admission_type)

```

# Down sample to balance data

```{r}
#Downsample
train_down <- downSample(subset(train_raw, select = -c(readmitted)), train_raw[["readmitted"]], list = FALSE)

names(train_down)[names(train_down) == "Class"] <- "readmitted"

#write.csv(train_down, "C:\\Users\\lilyy\\OneDrive - The University of Sydney (Students)\\5003\\5003 assignment 2\\train_down.csv")
```


## using range() 


```{r}
tic()
set.seed(123)
# Fit model using rager
ranger_model_train_down <- ranger (readmitted ~., data = train_down, importance = "impurity_corrected")
ranger_model_train_down
importance_pvalues(ranger_model_train_down, method = "janitza")



# Predict test data
pred_rg_test_train_down <- predict(ranger_model_train_down, data = test_raw)
pred_rg_test_train_down_pred <- factor(pred_rg_test_train_down$predictions, order = TRUE, levels = c("NO", ">30", "<30"))

#Evaluate prediction 
confusionMatrix(pred_rg_test_train_down_pred, test_raw$readmitted, mode = "everything")
toc()
``` 

## Ordinal forest

```{r}
# Ordinal tree model
tic()
ordforres_model_train_down  <- ordfor(depvar="readmitted", data=train_down)
ordforres_model_train_down 
toc()

# Predict test data
ordforres_model_train_down <- predict(ordforres_model_train_down, newdata = test_raw)


#Evaluate prediction 
confusionMatrix(ordforres_model_train_down$ypred, test_raw$readmitted, mode = "everything")
```


## Ranger using Lasso selected features only

```{r}
## Lasso Selected feature only
train_down_lasso <- train_down[,c("race","gender","age","num_lab_procedures","diag_3","number_diagnoses","glipizide","pioglitazone","rosiglitazone", "insulin","admission_source", "discharge_disposition","admission_type", "readmitted")]

test_raw_lasso <- test_raw[,c("race","gender","age","num_lab_procedures","diag_3","number_diagnoses","glipizide","pioglitazone","rosiglitazone", "insulin","admission_source", "discharge_disposition","admission_type", "readmitted")]

tic()
set.seed(123)
# Fit model using rager
ranger_model_train_down_lasso <- ranger (readmitted ~., data = train_down_lasso)
ranger_model_train_down_lasso


# Predict test data
pred_rg_test_train_down_lasso <- predict(ranger_model_train_down_lasso, data = test_raw_lasso)
pred_rg_test_train_down_lasso_pred <- factor(pred_rg_test_train_down_lasso$predictions, order = TRUE, levels = c("NO", ">30", "<30"))

#Evaluate prediction 
confusionMatrix(pred_rg_test_train_down_lasso_pred, test_raw$readmitted, mode = "everything")
toc()

```


## Ranger and Cross validation hyperparameter tuning


```{r}
# Grid
tic()
set.seed(123)
grid <- expand.grid(
  num.trees = c(1000, 2000, 4000, 6000, 8000, 10000), 
  mtry = c(2,3,4,5,6)
)

# Cross validation for tuning hyperparameters
fold <- createFolds(train_down[["readmitted"]], k = 5)
results <- data.frame()
for(i in 1:nrow(grid)){
  OBB_error <- c()
  for (k in 1:5){
    rf <- ranger(
      formula = readmitted ~.,
      data = train_down[fold[[k]],],
      num.trees = grid$num.trees[i],
      mtry = grid$mtry[i],
      importance = "impurity")
    OBB_error = append(OBB_error, rf$prediction.error)}

  results= rbind(results,merge(grid[i,],mean(OBB_error)))
}
head(results[order(results$y),], 5)

toc()

```


## Fit model with best hyperparameters 

```{r}
tic()
set.seed(123)
# Fit model using rager
ranger_model_train_down <- ranger (readmitted ~., data = train_down,  num.trees = 8000, mtry = 2, importance = "impurity_corrected")
ranger_model_train_down
importance_pvalues(ranger_model_train_down, method = "janitza")



# Predict test data
pred_rg_test_train_down <- predict(ranger_model_train_down, data = test_raw)
pred_rg_test_train_down_pred <- factor(pred_rg_test_train_down$predictions, order = TRUE, levels = c("NO", ">30", "<30"))

#Evaluate prediction 
confusionMatrix(pred_rg_test_train_down_pred, test_raw$readmitted, mode = "everything")
toc()
```


