---
title: "Group 10 STAT5003 Assignment Stage 2"
author: "Group 10"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
seed.value <- 500310
set.seed(seed.value)

install.custom <- function(package.name){
  if(!(package.name %in% row.names(installed.packages()))){
    install.packages(package.name)
  } else {
    print(paste0(package.name, " is already installed."))
  }
  library(package.name, character.only = T)
}

install.custom("purrr")
package_list <- c("broom"
                  , "ggplot2"
                  ,"tidyverse"
                  , "lubridate"
                  , "knitr"
                  , "janitor"
                  , "gridExtra"
                  , "sf"
                  , "dplyr"
                  , "ggpubr"
                  , "patchwork"
                  , "corrplot"
                  , "ggcorrplot"
                  , "matrixStats"
                  , "naniar"
                  , "devtools"
                  , "datapasta" 
                  , "data.table"
                  , "dtplyr"
                  , "tidymodels"
                  , "xgboost"
                  , "vip"
                  , "GGally"
                  , "glmnet"
                  , "ggthemes"
                  , "tidytext"
                  , "rmarkdown"
                  , "openxlsx"
                  #, "xlsx"
                  , "Hmisc"
                  , "mice"
                  , "corrplot"
                  , "missForest"
                  )

map(package_list, ~install.custom(.x))
```

# Read in data

```{r}
df.raw.train <- read_csv("data/train_raw.csv")
train_rep_oversampled <- read_csv("data/train_rep_oversampled.csv")
# train_rep_oversampled <- read_csv("data/train_rep_oversampled.csv")

test_raw <- read_csv("data/test_raw.csv")
```

# Data conversion

```{r}
# Convert character to factor in train_raw data
train_rep_oversampled$race <- factor(train_rep_oversampled$race)
train_rep_oversampled$gender <- factor(train_rep_oversampled$gender)
train_rep_oversampled$age <- factor(train_rep_oversampled$age, order = TRUE, levels = c("[0-10)", "[10-20)", "[20-30)", "[30-40)", "[40-50)", "[50-60)", "[60-70)", "[70-80)", "[80-90)", "[90-100)"))
train_rep_oversampled$diag_1 <- factor(train_rep_oversampled$diag_1 )
train_rep_oversampled$diag_2 <- factor(train_rep_oversampled$diag_2)
train_rep_oversampled$diag_3 <- factor(train_rep_oversampled$diag_3)
train_rep_oversampled$A1Cresult <- factor(train_rep_oversampled$A1Cresult)
train_rep_oversampled$metformin <- factor(train_rep_oversampled$metformin)
train_rep_oversampled$glipizide <- factor(train_rep_oversampled$glipizide)
train_rep_oversampled$glyburide <- factor(train_rep_oversampled$glyburide)
train_rep_oversampled$pioglitazone <- factor(train_rep_oversampled$pioglitazone)
train_rep_oversampled$rosiglitazone <- factor(train_rep_oversampled$rosiglitazone)
train_rep_oversampled$insulin  <- factor(train_rep_oversampled$insulin )
train_rep_oversampled$change <- factor(train_rep_oversampled$change)
train_rep_oversampled$diabetesMed <- factor(train_rep_oversampled$diabetesMed)
train_rep_oversampled$readmitted <- factor(train_rep_oversampled$readmitted, order = TRUE, levels = c("NO", ">30", "<30"))
train_rep_oversampled$admission_source <- factor(train_rep_oversampled$admission_source)
train_rep_oversampled$discharge_disposition <- factor(train_rep_oversampled$discharge_disposition)
train_rep_oversampled$admission_type <- factor(train_rep_oversampled$admission_type)

# Check feature type in train_raw data after conversion
# str(train_raw)

# Convert character to factor in test_raw data
test_raw$race <- factor(test_raw$race)
test_raw$gender <- factor(test_raw$gender)
test_raw$age <- factor(test_raw$age, order = TRUE, levels = c("[0-10)", "[10-20)", "[20-30)", "[30-40)", "[40-50)", "[50-60)", "[60-70)", "[70-80)", "[80-90)", "[90-100)"))
test_raw$diag_1 <- factor(test_raw$diag_1 )
test_raw$diag_2 <- factor(test_raw$diag_2)
test_raw$diag_3 <- factor(test_raw$diag_3)
test_raw$A1Cresult <- factor(test_raw$A1Cresult)
test_raw$metformin <- factor(test_raw$metformin)
test_raw$glipizide <- factor(test_raw$glipizide)
test_raw$glyburide <- factor(test_raw$glyburide)
test_raw$pioglitazone <- factor(test_raw$pioglitazone)
test_raw$rosiglitazone <- factor(test_raw$rosiglitazone)
test_raw$insulin  <- factor(test_raw$insulin )
test_raw$change <- factor(test_raw$change)
test_raw$diabetesMed <- factor(test_raw$diabetesMed)
test_raw$readmitted <- factor(test_raw$readmitted, order = TRUE, levels = c("NO", ">30", "<30"))
test_raw$admission_source <- factor(test_raw$admission_source)
test_raw$discharge_disposition <- factor(test_raw$discharge_disposition)
test_raw$admission_type <- factor(test_raw$admission_type)
```

```{r}
ggplot(train_rep_oversampled, aes(readmitted)) + geom_bar()
```

# GBM Model

```{r}
# Train_set <- train_rep_oversampled[sample(nrow(train_rep_oversampled), 100), ]
Train_set <- train_rep_oversampled
Test_set <- test_raw

CV_set <- vfold_cv(Train_set, v=10)

xgb.recipe <- recipe(
  as.formula(
    readmitted ~ .,
  ),
  data = Train_set
) %>% 
  step_dummy(all_nominal_predictors())

xgb.model <- boost_tree() %>% 
  set_args(
    mtry = tune(),
    trees = 500,
    min_n = tune(),
    tree_depth = tune(),
    learn_rate = tune(),
    loss_reduction = tune()
  ) %>% 
  set_engine("xgboost"
             , objective="multi:softprob"
             , num_class=3
             ) %>% 
  set_mode("classification")

xgb.workflow <- workflow() %>% 
  add_recipe(xgb.recipe) %>% 
  add_model(xgb.model)
  
xgb.params <- parameters(
  finalize(mtry(), Train_set),
  min_n(),
  tree_depth(),
  learn_rate(),
  loss_reduction()
)
  
xgb.grid <- xgb.params %>% 
  grid_max_entropy(
    size = 30
  )

#install.custom("doParallel")
doParallel::registerDoParallel()
xgb.tune <- xgb.workflow %>% 
  tune_grid(
    resamples = CV_set ,
    grid = xgb.grid,
    control = control_grid(save_pred = TRUE, verbose=T)
  )
  
# saveRDS(xgb.tune, "GBM/xgb_tune_SMOTE_A.rds")
```

# Tuned metrics

```{r}
collect_metrics(xgb.tune)
show_best(xgb.tune, "roc_auc")
show_best(xgb.tune, "accuracy")

best_auc <- select_best(xgb.tune, "roc_auc")
best_acc <- select_best(xgb.tune, "accuracy")

write_csv(collect_metrics(xgb.tune), "GBM/xgb_tune_REP_B_metrics.csv")
write_csv(best_auc, "GBM/xgb_tune_REP_B_metrics_bestAUC.csv")
write_csv(best_acc, "GBM/xgb_tune_REP_B_metrics_bestACC.csv")
```

# Final Model

```{r}
xgb.workflow.final <- xgb.workflow %>% 
  finalize_workflow(best_auc)

xgb.model.fit <- xgb.workflow.final %>% 
  fit(data = Train_set)
saveRDS(xgb.model.fit, "GBM/xgb_tune_REP_B_modelfit.rds")

Train_AvE <- data.frame(obs = Train_set$readmitted, preds = predict(xgb.model.fit, new_data = Train_set)$.pred_class) %>% 
  mutate_if(is.factor, as.character)

Test_AvE <- data.frame(obs = Test_set$readmitted, preds = predict(xgb.model.fit, new_data = Test_set)$.pred_class) %>% 
  mutate_if(is.factor, as.character)

cmat_train <- Train_AvE %>% conf_mat(obs, preds) 
cmat_test <- Test_AvE %>% conf_mat(obs, preds)

summary(cmat_train)
summary(cmat_test)
autoplot(cmat_test, type = "heatmap")

caret::confusionMatrix(as.factor(Test_AvE$obs), as.factor(Test_AvE$preds), mode = "everything")

```

# ROC 

```{r}
probs <- predict(xgb.model.fit, new_data = Test_set, type = "prob")

Test_AvE %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(`<30` = probs$`.pred_<30`
         , `>30` = probs$`.pred_>30`
         , NO = probs$.pred_NO) %>% 
  roc_curve(obs, `<30`:NO) %>%
  autoplot()
```

# VIP

```{r}
vip(xgb.model.fit %>% extract_fit_parsnip())
```



